pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                     sh '''
                        mkdir -p .cache/go-build .cache/go-mod
                        GOCACHE="$PWD/.cache/go-build" \
                        GOMODCACHE="$PWD/.cache/go-mod" \
                        go test -v ./...
                    '''
                }
            }
        }
    }
}
